Repository zinuu4/Severyanochka, pull requests merged in 2023-09, with the labels that each got.

#18 ci: conventional semantic commit and versioning and some CI
  .github/dependabot.yml
  .github/workflows/canmerge.yml
  .github/workflows/dependabot-automerge.yml
  .github/workflows/nextjs-bundle-analysis.yml
  .github/workflows/release.yml
  .github/workflows/server.yml
  .gitignore
  .husky/commit-msg
  client/package.json
  client/yarn.lock
  commitlint.config.js
  package.json
Labels: auto-merge

#15 feat(product): ✨ change product id to article
  server/src/controllers/product.controller.js
  server/src/models/product.model.js
  server/src/routes/v1/product.route.js
  server/src/services/product.service.js
Labels: auto-merge

#13 Features/product card
  client/assets/common/alert-circle.svg
  client/assets/common/heart.svg
  client/assets/common/message.svg
  client/assets/common/search.svg
  client/assets/common/star.svg
  client/jest.setup.js
  client/next.config.mjs
  client/package.json
  client/public/lays.png
  client/public/sprite.svg
  client/src/app/globals.scss
  client/src/app/styles/_vars.scss
  client/src/entities/product-card/index.ts
  client/src/entities/product-card/ui/index.tsx
  client/src/entities/product-card/ui/info/index.ts
  client/src/entities/product-card/ui/info/prices/index.ts
  client/src/entities/product-card/ui/info/prices/styles.module.scss
  client/src/entities/product-card/ui/info/prices/ui.tsx
  client/src/entities/product-card/ui/info/styles.module.scss
  client/src/entities/product-card/ui/info/ui.tsx
  client/src/entities/product-card/ui/styles.module.scss
  client/src/entities/product-card/ui/top/index.ts
  client/src/entities/product-card/ui/top/styles.module.scss
  client/src/entities/product-card/ui/top/ui.tsx
  client/src/features/add-to-cart/index.ts
  client/src/features/add-to-cart/styles.module.scss
  client/src/features/add-to-cart/ui.tsx
  client/src/features/add-to-favorites/index.ts
  client/src/features/add-to-favorites/styles.module.scss
  client/src/features/add-to-favorites/ui.tsx
  client/src/shared/types/index.d.ts
  client/src/shared/types/index.ts
  client/src/shared/ui/button/styles.module.scss
  client/src/shared/ui/button/ui.tsx
  client/src/shared/ui/icon/sprite.gen.ts
  client/src/shared/ui/index.ts
  client/src/shared/ui/input/index.ts
  client/src/shared/ui/input/styles.module.scss
  client/src/shared/ui/input/ui.test.tsx
  client/src/shared/ui/input/ui.tsx
  client/src/shared/ui/notice/index.ts
  client/src/shared/ui/notice/styles.module.scss
  client/src/shared/ui/notice/ui.tsx
  client/src/shared/ui/rating/index.ts
  client/src/shared/ui/rating/styles.module.scss
  client/src/shared/ui/rating/ui.tsx
  client/src/shared/ui/tooltip/index.ts
  client/src/shared/ui/tooltip/styles.module.scss
  client/src/shared/ui/tooltip/ui.tsx
  client/src/widgets/header/ui/catalog/styles.module.scss
  client/src/widgets/header/ui/catalog/trigger-btn/ui.tsx
  client/src/widgets/header/ui/index.tsx
  client/src/widgets/product-card-with-actions/index.ts
  client/src/widgets/product-card-with-actions/styles.module.scss
  client/src/widgets/product-card-with-actions/ui.tsx
  client/yarn.lock
Labels: auto-merge

#11 feat(product): ✨ add product request validation
  client/src/shared/ui/index.ts
  package-lock.json
  server/src/controllers/product.controller.js
  server/src/models/product.model.js
  server/src/routes/v1/product.route.js
  server/src/validations/index.js
  server/src/validations/product.validation.js
  yarn.lock
Labels: auto-merge

#24 Features/client husky and prettier
  client/.eslintrc.json
  client/.husky/pre-commit
  client/.prettierignore
  client/.prettierrc.json
  client/.stylelintrc.json
  client/commitlint.config.js
  client/jest.config.js
  client/package.json
  client/src/app/globals.scss
  client/src/app/styles/_text.scss
  client/src/app/styles/_vars.scss
  client/src/entities/product-card/ui/info/prices/styles.module.scss
  client/src/entities/product-card/ui/info/styles.module.scss
  client/src/entities/product-card/ui/styles.module.scss
  client/src/entities/product-card/ui/top/styles.module.scss
  client/src/features/add-to-cart/styles.module.scss
  client/src/features/add-to-favorites/styles.module.scss
  client/src/shared/ui/button/styles.module.scss
  client/src/shared/ui/checkbox/styles.module.scss
  client/src/shared/ui/input/styles.module.scss
  client/src/shared/ui/notice/styles.module.scss
  client/src/shared/ui/rating/styles.module.scss
  client/src/shared/ui/toggle/styles.module.scss
  client/src/shared/ui/tooltip/styles.module.scss
  client/src/widgets/header/ui/catalog/menu/styles.module.scss
  client/src/widgets/header/ui/catalog/trigger-btn/styles.module.scss
  client/src/widgets/product-card-with-actions/styles.module.scss
  client/yarn.lock
  server/yarn.lock
Labels: review-required

#33 ✨ feat(banner): hero banner of home page
  client/public/banners/fruit-colored-pattern.png
  client/public/banners/vegetables-card-banner.png
  client/src/app/page.tsx
  client/src/app/styles/_vars.scss
  client/src/page-s/home/index.ts
  client/src/page-s/home/ui/hero-banner/config/index.ts
  client/src/page-s/home/ui/hero-banner/index.ts
  client/src/page-s/home/ui/hero-banner/styles.module.scss
  client/src/page-s/home/ui/hero-banner/ui.tsx
  client/src/page-s/home/ui/home.tsx
  client/src/shared/ui/index.ts
  client/src/shared/ui/promotion-card/config/index.ts
  client/src/shared/ui/promotion-card/index.ts
  client/src/shared/ui/promotion-card/styles.module.scss
  client/src/shared/ui/promotion-card/ui.tsx
Labels: enhancement, review-required

#38 :sparkles: feat(crud): vacancy crud and model
  server/.gitignore
  server/src/controllers/index.js
  server/src/controllers/vacancy.controller.js
  server/src/models/index.js
  server/src/models/vacancy.model.js
  server/src/routes/v1/index.js
  server/src/routes/v1/vacancy.route.js
  server/src/services/index.js
  server/src/services/vacancy.service.js
  server/src/validations/custom.validation.js
  server/src/validations/index.js
  server/src/validations/vacancy.validation.js
Labels: enhancement, review-required
